### ISSUE TITLE
Separating patchlevel and special version

### ISSUE THREAD

**Issue by serverhorror** [semver/semver.org#15]
It should be allowed (but not required) to separate the patchlevel and special version number by using a `~` (tilde), the regex for a valid version number (including tags) would then be:

^v?(?P<major>\d+).(?P<minor>\d+).?P<patchlevel>\d+)~?(?P<special>[a-z]\w+[\d+])?$

If you use this pattern (in python don't know about compatibility to other regex implementations) you can get a nice dictionairy with the keys set to "major", "minor", "patchlevel", "special". This allows easy comparison and further validation

**Comment by bclinkinbeard** [comment]
I agree with a separator but prefer a more standard character, like a dash. v1.0.0-beta is much more readable than v1.0.0beta

Any chance this tweak can/will be blessed and considered valid?

**Comment by alblue** [comment]
Note that the OSGi spec uses a '.' for the separator between both numeric versions and the optional alpha version. Note that this does not introduce ambiguity, since 1.beta is evaluated to be 1.0.0.beta since it can be nothing else. A special character (or no character) is not necessary; and in fact, 1.2.3beta in OSGi would equate to 1.2.0.3beta, since '3beta' is alphabetic and defaults are zero for numeric values.

**Comment by mojombo** [comment]
SemVer 1.0.0 will use a decimal point (period) as the mandatory separator for what will be called pre-release versions. For instance: 1.2.3.alpha. This is visually easier to parse and consistent with an extended decimal-type thing.

**Comment by tbull** [comment]
I really like the dash much more than the dot for that purpose.

**Comment by mlassau** [comment]
I think that the dash is quite a common pattern.

Also note that it is sometimes used for "flavours" as well as "pre-release versions"
eg 4.2.1-x86 vs 4.2.1-i64

(examples: http://www.apache.org/dist/tomcat/tomcat-7/v7.0.12/bin/ )
