### ISSUE TITLE
https responds for www.semver.org but serves a github.com certificate

### ISSUE THREAD

**Issue by shaunbrady** [semver/semver.org#207]
https://semver.org works as expected.

**Comment by haacked** [comment]
www.semver.org immediately redirects to semver.org on my machine.

**Comment by haacked** [comment]
Oh wait, i see it.

**Comment by haacked** [comment]
In order to reproduce this, I need to explicitly type `https://www.semver.org` into the browser address bar.

**Comment by hartwork** [comment]
> Warning: If your domain has HTTPS enforcement enabled, GitHub Pages' servers will not automatically route redirects. You must configure www subdomain and root domain redirects with your domain registrar.

Not sure if I read https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/ correctly, but it seems like a GitHub limitation and would need a self-made third party webserver that does nothing but Let's Encrypt SSL with auto-refresh and a redirect to GitHub. I hope that's _not_ what is needed, would not be very pretty. Do you read that page the same way?

**Comment by haacked** [comment]
That's my understanding.

**Comment by alexandrtovmach** [comment]
@haacked Do you have any idea how we can solve this issue? Who is the owner of domain and able to change config? Thanks

**Comment by haacked** [comment]
I own the domain. Let me know what DNS changes are needed.

**Comment by hartwork** [comment]
> I own the domain. Let me know what DNS changes are needed.

`www.semver.org.` has a CNAME record to `semver.github.io.` right now which in turn only serves a 404 page right now. So that CNAME would need to be pointed to a working server, e.g. to `semver.org.` (without www) so that the same IP can serve both hostnames.

Then, that server needs to serve an SSL certificate that contains two hostnames, both `semver.org` and `www.semver.org`. That may or may not need a change to https://github.com/semver/semver.org/blob/gh-pages/CNAME (but GitHub provides a UI for changing that file).

Let's start with step 1 and see how far we get?

**Comment by haacked** [comment]
Before I make any changes, here's what is set up currently.

![image](https://user-images.githubusercontent.com/19977/84324756-0ccf9f00-ab2e-11ea-806f-240fa4033a5c.png)

Notice I have an ALIAS for semver.org to semver.github.io.

**Comment by hartwork** [comment]
Maybe I should note that to make GitHub serve https://semver.github.io it would take a repository https://github.com/semver/semver.github.io . Quoting from https://help.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites:

> To publish an organization site, you must create a repository owned by an organization that's named `<organization>.github.io`

**Comment by haacked** [comment]
Those may be the new rules, but note the legacy rules state:

> Repositories using the legacy <user>.github.com naming scheme will still be published, but visitors will be redirected from http(s)://<username>.github.com to http(s)://<username>.github.io. If both a <user>.github.com and <user>.github.io repository exist, only the <user>.github.io repository will be published.

Also the same docs state:

> Unless you're using a custom domain, user and organization sites are available at http(s)://<username>.github.io or http(s)://<organization>.github.io.

So everything is configured correctly here as far as https://semver.org/ goes.

The problem is this, our CNAME file in the repo says `semver.org`. AFAIK, GitHub's Let's Encrypt integration issues a certificate for semver.org only, not `www.semver.org` as well.

So if anyone comes to visit https://www.semver.org/, they get a certificate error. I think the ideal solution would be for us to have a redirect from www.semver.org -> semver.org. However, that still requires a certificate for `www.semver.org` to do it properly.

This seems like a feature request for GitHub.

**Comment by haacked** [comment]
Looks like we may need to change the CNAME file to have `www.semver.org`.

> If you are using an apex domain as your custom domain, we recommend also setting up a www subdomain. If you configure the correct records for each domain type through your DNS provider, GitHub Pages will automatically create redirects between the domains. For example, if you configure www.example.com as your custom domain for your site, and you have ALIAS and CNAME records set up for the apex and www domains, then example.com will redirect to www.example.com.

**Comment by haacked** [comment]
So the best we can do is have `https://semver.org` redirect to `https://www.semver.org`. Doing the opposite does not seem possible with GitHub pages.

**Comment by alexandrtovmach** [comment]
@haacked Thanks for investigation 👍

**Comment by alexandrtovmach** [comment]
I've reached out with GitHub support to double check this moment, and here what we have:

![image](https://user-images.githubusercontent.com/28801003/84513860-bfd8fd80-acd2-11ea-8f9b-342d488650d0.png)

We cannot fix it, so I think this issue should be closed 🤷 Feel free to re-open or create a new one, if there are some updates from GitHub side.

**Comment by hartwork** [comment]
> ![image](https://user-images.githubusercontent.com/28801003/84513860-bfd8fd80-acd2-11ea-8f9b-342d488650d0.png)

Wow, that's sad.
