### ISSUE TITLE
Include an option version for packaging-specific changes

### ISSUE THREAD

**Issue by jude** [semver/semver.org#30]
When packaging software in RPM, deb or similar formats, bugs can be introduced in the packaging code which require a new package to be released even when none of the non-packaging code has changed.  Therefore, please consider adding an additional packaging-specific version to the semver for projects which maintain their own packaging.

Suggested new rules would be:
- If there is packaging-related source included in the project, include a '-R' suffix to the version where R is an integer and R>0
- R increments whenever a packaging-only change is fixed.  Examples of packaging-only changes would be spec file changes for rpm packages or changes under the debian directory for deb packages.
- If the X, Y, or Z values change, R should be reset back to 1.

In RPM packaging, the R value is surfaced as the 'Release' tag.  In debian packaging, this would be the debian_revision

**Comment by tbull** [comment]
I think this is outside the domain of semver. Since this is an issue specific to the particular package system, would it hurt if they invented their own package-specific versioning scheme independent of the version of the packaged software? They can use whatever they want as long as the package version is clearly distinguishable from the software version. For example, they could separate their internal number with an underscore. I think, the FreeBSD ports do it so.

**Comment by mojombo** [comment]
I agree. This is outside the scope of SemVer and would only result in a more confusing and elaborate spec (which is the opposite of what I'm striving for). Specific packaging semantics should be established as extensions to SemVer in a responsible way and documented as such.
