### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by trans** [semver/semver.org#36]
Is the tagging spec really even necessary? Is that really important to the purpose of semver?  I point out that subversion repos often used `REL` prefixes and not `v` prefixes.

Personally I stopped using any prefix at all. It makes it very clear what is a release and what is a developers branch, and sorts even better than using `v`. I discussed this once on a git mailing list and the feedback I received suggested the use of `v` has arisen simply b/c that is what Linus did on his projects, but there isn't any technical reason that it must be so.

**Comment by postmodern** [comment]
I actually think the `v` might be necessary, in the case that someone uses date tags (ex: `4.20.2010`). The `v` helps clarify it is in fact a version.

**Comment by mojombo** [comment]
I think the SemVerTag spec is important even if only to remind people that they should be tagging their releases. It is optional for a reason, and that is because many people have pre-existing noncompliant formats or don't like the vX.Y.Z format for some reason.

The format is arbitrary, but a prefixed 'v' is common practice already and virtually guarantees that all tags will show up together in a list and exclude ambiguous matches as @postmodern has noted.

**Comment by trans** [comment]
If one used date tags then it makes some sense (though one could distinguish `.` and `-` if really necessary). I've never heard of anyone using date tags before, and I don't see a reason to do so --can't you always look up a commit by date? But in any case, it's not a big deal, I have found release tags without the the `v` to work well, and to me a better choice. It would be nice if SemVerTag were open to it --perhaps a broader mandate to just have a consistent release tagging scheme containing the version. But as pointed out, SemVerTag is optional and non-essential to more fundamental concerns of SemVer. Thanks.
