### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by xeanhort** [semver/semver.org#381]
Some catalan translation fixes:

- Change "pre-llençament" to "pre-llançament".
- Change "NO HAN D’estar buits" to "NO HAN d’estar buits".
- Change "amb amb" to "amb".

I guess @mikaku is in charge

**Comment by mikaku** [comment]
> Change "NO HAN D’estar buits" to "NO HAN d’estar buits".

Hmm, I'm a bit confused on this.

As stated in the beginning of that document, I've translated the words "SHALL" by "HAN DE", and "NOT SHALL" by "NO HAN DE". That's why you might see the forms like "NO HAN D'", depending if the next word must be apostrophized.

Your suggestion to lowercase 'DE' does mean to change the translation to just "HAN" and '"NO HAN" in the rest of the document?

**Comment by xeanhort** [comment]
> Your suggestion to lowercase 'DE' does mean to change the translation to just "HAN" and '"NO HAN" in the rest of the document?

That's one option. It was just an aesthetic suggestion to facilitate reading. You are the one to decide :)

**Comment by mikaku** [comment]
Well, I'll keep it as it is. It looks correct enough for me by now.

**Comment by mikaku** [comment]
@xeanhort the PR needs to be approved by at least one person in order to be merged. :wink:

**Comment by xeanhort** [comment]
> @xeanhort the PR needs to be approved by at least one person in order to be merged. 😉

Done!

**Comment by mikaku** [comment]
@xeanhort, thanks.
