### ISSUE TITLE
Spec prescribes ambiguous version tags

### ISSUE THREAD

**Issue by ryangreenberg** [semver/semver.org#42]
Spec states:

> This sub-specification SHOULD be used if you use a version control system (Git, Mercurial, SVN, etc) to store your code. Using this system allows automated tools to inspect your package and determine SemVer compliance and released versions.
> 
> When tagging releases in a version control system, the tag for a version MUST be "vX.Y.Z" e.g. "v3.1.0".

Given that multiple software projects may be stored in the same repository, a tag like "v3.1.0" is ambiguous with respect to which software project it applies to. In some VCS this may not be an issue (with SVN you can have a tags directory for each project); for others it will be (tags in git exist in a shared namespace for the whole repo).

One solution would be to permit the name of the project in the tag name, e.g. "foo-3.1.0", "bar-2.3.4".

**Comment by gavenkoa** [comment]
Storing a couple of projects in single DVCS repo is BAD idea.

Avoid this as possible as you go in nightmare when try move changes across foo-1.0 to foo-2.1 when in this time bar-1.3 go to bar-3.0!

You start use cherry-picking/transplant and lose idea behind DVCS.

**Comment by ryangreenberg** [comment]
From the perspective of the semantic versioning spec, does it matter whether certain repository management practices are good or bad? With both DVCS and centralized VCS, I've used repos that contain multiple projects. My understanding is that all (or at least most) of Google's projects are stored in a single Perforce repository.

Given these facts, following the spec is a non-starter in these cases. I'm suggesting a pragmatic approach where the spec is changed so it can realistically be followed.

**Comment by gavenkoa** [comment]
@ryangreenberg I see _technical_ problems when store multiply project in single DVCS repo. You damage DAG cleanness and as result make marge job hard. So you lose any benefits from DVCS.

Storing many projects in single repo come from SVN. And must be stay in SVN as it is usual workflow for SVN (based on its architecture)!

I am not talking about semantic background. In this field I absolutely agree with you.

Your request for version naming also take one thing why multiproject approach in single DVCS repo is bad.

We recently split one of our Mercurial repo into 3 as it contain independent part which can live by own life. As exist dependency relation between them it was become a problem of SCM (Configuration Management) and resolved by appropriated tools and methodologies.

Split of repo take 30 min to learn Mercurial syntax and some tests and 5 min for itself (for a large history base).

NOTE. SVN does not need your suggested as it internally architecture allow store many project at same time!

One case that I can miss if all project in your repo start history from zero rev and project branches don't share any commits. In that case you also right.

**Comment by sr105** [comment]
Instead of debating repository architecture, why not just define the initial semver tag to be "semver[PREFIX]" where [PREFIX] is optional. In Ryan's examples above, he would have two initial tags, "semverfoo-" and "semverbar-". These would instruct any automated tools of what to look for and how to parse future tags.

**Comment by gavenkoa** [comment]
@sr105 Why? Some use cases are rare and not necessary and someone can argue that such usage is incorrect.

You don't put third wheel to motorcycle just because it fall when it off.

semver does not cover _ALL_ possible cases.... anyway.

**Comment by sr105** [comment]
@gavenkoa: Many people still use the single repo approach. It seems limiting to say that they won't be supported (and easily, too, as I've shown) because of a philosophical difference. My suggestion is really minor and works in either case. Also, I could see this feature being used in single-repo setups because some people may want more than just "vX.Y.Z"

**Comment by gavenkoa** [comment]
@sr105 I still think that store independent project in single DVCS repo is bad idea for setup then projects dir live side by side in dir hierarchy.

If you put tag for one project it propagated to another. This is semantically wrong.

But if every project start its history from ZERO revision - that another case and PRJ-vX.Y.Z - nice schema! But in this case why simply store history in separate repos? This provide convenient to point to project more independent as different project have different path (git://PRJ111.int  and git://PRJ222.int). In case of single repo you must provide a path and a PRJ part of tag name.

But I can some miss...

**Comment by bobthecow** [comment]
It is perfectly acceptable to store multiple projects in different branches in Git. I don't know if you noticed, but _this project_ has two different branches, each of which would need to be tagged independently... So if the tags for this project are to follow SemVer, there should be a provision for tag prefixes.

**Comment by gavenkoa** [comment]
@bobthecow I rethink about naming and understand the need to specify **THAT** is tagged by version. But this **MUST** be out of scope of semver (as I think :) ) because it is already exist practice to use _project name_ as prefix: PROJ_major.minor.rev.

So just add to your naming schema prefix, but don't mix this spec with your own need.

**Comment by gavenkoa** [comment]
@bobthecow _this project has two different branches, each of which would need to be tagged independently_

Good point ))

I argue that multi-project repo appear because of limitation of services (in contrast Sourceforge allow host multiply repos for single project) or laziness of admins (to simplify maintenance, granting permissions, etc.)

I would like to hear another case why use unrelated branches in single repo??

**Comment by mojombo** [comment]
I'm strongly considering removing the SemVerTag sub-spec from SemVer entirely because it's becoming clear that there are too many variations on how people craft version tags for any single spec to ever be appropriate. It is also confusingly worded right now, the intention is that following SemVerTag is OPTIONAL, but if you do decide to follow it, you MUST do it in a specific way.

**Comment by mojombo** [comment]
I've decided, and SemVerTag will be removed from the SemVer 1.0 spec. It is too divisive and acts only as a distraction from what SemVer is trying to achieve.

**Comment by SamStephens** [comment]
Tom, is there anywhere SemVerTag is hosted now it's been removed from SemVer? We're using SemVerTag, and I'd like a reference location to link to.

Thanks
