### ISSUE TITLE
1.0.0-rc.1 Breaks Backwards Compatibility

### ISSUE THREAD

**Issue by theory** [semver/semver.org#49]
Overall, I welcome the changes in [this commit](https://github.com/mojombo/semver.org/commit/9906c3febaef4a5e4053eeac6c51b82d29a48a06). When we talked last summer, you mentioned adding `-` as a separator between the patch version and the pre-release string. I’m glad to see it. I also like how you managed to avoid adding a fourth digit (`x.x.x.x`) by allowing the pre-release string and the new build string to also be dot-delimited.

However, the new requirement of the `-` between the patch version and the prerelease string means that valid 1.0.0 semantic versions, such as `1.0.0b3` are no longer valid. Given that I maintain two libraries that validate semantic versions, I would prefer that backwards compatibility be maintained. As such, could the `-` be optional if there are no dots in the prerelease string? Even if the docs say that it may not be used going forward, I think that existing semvers in the wild should still be valid, even if it's only a footnote that says so.

Thoughts?

Thanks,

David

**Comment by dvarrazzo** [comment]
Hello,

while I happen to prefer the new versioning scheme too, you have moved the spec version number backwards from 1.0.0 to 1.0.0-rc1. There is software that has been written and documented as following the semver 1.0 spec and pgxn requires all the submitted packages to respect this convention.
- http://pgxn.org/spec/#Version.Numbers
- http://pgxn.org/dist/semver/doc/semver.html
- https://metacpan.org/module/SemVer
- https://github.com/dvarrazzo/pgxnclient/blob/devel/pgxnclient/utils/semver.py

The spec we all refer is no more published and only to be found in the git log.

Please publish a web page documenting what has been known for long time as the version 1.0.0 of the spec, so that we can refer to it, and feel free to make all the improvements you want to the spec but calling it 1.1.0 if it keeps backward compatibility (if any 1.0-valid version is also 1.1-valid) or 2.0.0 if it doesn't (as it is currently the case).

The current situation breaks point 2 (strict increment) and 9 (backward compatibility) of the spec, but more generally casts a very dark shadow over the credibility of the project.

**Comment by mojombo** [comment]
@dvarrazzo you are indeed correct. I mistakenly thought I had not yet released the official 1.0.0 yet, but I was wrong, it did state that on the site for some time. I will update the spec and site to 2.0.0-rc.1 soon. Thanks for pointing this out.

**Comment by mojombo** [comment]
The site is now updated and has a link to the v1.0.0 spec in the header. Sorry for the confusion.

**Comment by theory** [comment]
Thanks. What about the compatibility issue?
