### ISSUE TITLE
This is called Unix shared library version numbering convention

### ISSUE THREAD

**Issue by gleb** [semver/semver.org#5]
- http://apr.apache.org/versioning.html
- http://www.freebsd.org/doc/en/books/developers-handbook/policies-shlib.html
- http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html
- http://home.bolink.org/ebooks/unix3/mac/ch05_04.htm

If you can make it popular in Ruby world you can call it whatever you please :-)  You should be able to find 10 (and probably 20) year old rants about how technology X does not do version numbering right, and should use Unix shared library standard.

It's funny, I chatted with Yehuda after his awesome RubyConf 2009 Gems presentation, where he talked about the right way to dependency management, suggesting he add this to the list of best practices that Bundler encourages.   He didn't think it would be possible to evangelize this successfully.  I'd love to see you prove him wrong.

**Comment by jwheare** [comment]
I think the key point here is this, from semver.org:
"This is not a new or revolutionary idea. In fact, you probably do something close to this already. The problem is that "close" isn't good enough"

Most of those links don't seem as explicit, clear and well defined as what's on semver.org. The Apache example is an exception, though it's a little stuffy, harder to digest, specific to UNIX and differs a little in the conventions it codifies.

Anyway, it's a useful list of prior art.

**Comment by dlaidlaw** [comment]
This versioning is the same as described in OSGi as well and seems to be completely compatible. In OSGi the version is also specified in the manifest for the jar. This means it is available for tooling, which is very nice.

**Comment by mojombo** [comment]
Thanks for the links, they make for interesting reading. Semantic Versioning is very similar (sometimes identical) to other systems. My intention here is to take these good ideas, give them a nice name and place to live (not associated with any specific technology or platform) and evangelize the crap out of them in the hopes that I may one day benefit from a more standardized versioning ideal. I guess we'll see how it goes in the rubygem ecosystem. =)
