### ISSUE TITLE
Tag 2.0.0

### ISSUE THREAD

**Issue by theory** [semver/semver.org#66]
Is 2.0.0 Formally released? If so, a tag would be great. Thanks!

**Comment by haacked** [comment]
I knew I forgot something!

**Comment by haacked** [comment]
Done! Thanks for the reminder.

**Comment by rogeriopradoj** [comment]
I guess the tag was put on wrong SHA1!

5b8cd458b88557faf1c838d44374387083eefc89

It is a commit from 2009-12-29

@Haacked, could you take a look?

**Comment by haacked** [comment]
@rogeriopradoj doh! I tagged `master` but our default branch is `gh-pages`. My fault! Thanks for noticing!

**Comment by haacked** [comment]
I fixed it. Could you look again?

**Comment by theory** [comment]
That looks better, @Haacked.

**Comment by rogeriopradoj** [comment]
Yeah, I think it's fine now!

I have a question: when we started to merge the translations, the tag v2.0.0 will go forward with, or will be stucked with that commit?

I think it's is worth discussing about because the translations will change the layout of official page (including the links to the others languages), but probably will not change the english spec.

What do you say?

**Comment by haacked** [comment]
I think we should stick it to that commit. Makes it easy to tie that release to the corresponding release on mojombo/semver. Also, translations might come in later after master has moved forward.
