### ISSUE TITLE
The spec does not cover dependency management

### ISSUE THREAD

**Issue by schmidt** [semver/semver.org#9]
What should I do, if I update my own dependencies, while leaving my external API as is - patch  or major version update?

**Comment by mojombo** [comment]
That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you bumped the deps to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it's obviously a minor level increment.

I've added this as an FAQ to the site.

**Comment by schmidt** [comment]
Thanks for the quick reply and clarification.
